### ISSUE TITLE
The error of running ui.py 

### ISSUE THREAD

**Issue by ThePassedWind** [Jun-CEN/SegmentAnyRGBD#2]
The error output:

Traceback (most recent call last):
  File "ui.py", line 12, in <module>
    import gradio as gr
  File "//home/zhangzs/snap/anaconda3/envs/segment-anything/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "//home/zhangzs/snap/anaconda3/envs/segment-anything/lib/python3.8/site-packages/gradio/components.py", line 55, in <module>
    from gradio import processing_utils, utils
  File "//home/zhangzs/snap/anaconda3/envs/segment-anything/lib/python3.8/site-packages/gradio/utils.py", line 497, in <module>
    class AsyncRequest:
  File "//home/zhangzs/snap/anaconda3/envs/segment-anything/lib/python3.8/site-packages/gradio/utils.py", line 516, in AsyncRequest
    client = httpx.AsyncClient()
  File "//home/zhangzs/snap/anaconda3/envs/segment-anything/lib/python3.8/site-packages/httpx/_client.py", line 1395, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "//home/zhangzs/snap/anaconda3/envs/segment-anything/lib/python3.8/site-packages/httpx/_client.py", line 216, in _get_proxy_map
    return {
  File "//home/zhangzs/snap/anaconda3/envs/segment-anything/lib/python3.8/site-packages/httpx/_client.py", line 217, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "//home/zhangzs/snap/anaconda3/envs/segment-anything/lib/python3.8/site-packages/httpx/_config.py", line 336, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:1089/')

**Comment by JackyYang258** [comment]
It was the wrong proxy
try the commamd
```shell
unset ALL_PROXY
``` 
Don't worry it will only change the proxy in this terminal

**Comment by Jun-CEN** [comment]
Thanks a lot for your solution. Hope it works!
